MADE.Networking/Requests/Json/PostNetworkRequest.cs
MADE.Networking/Requests/Json/PutNetworkRequest.cs
MADE.Networking/Requests/NetworkRequest.cs

Adding a change to the project relating to issue #26 where the NetworkRequest did not support adding content to the request.

Issue #26 - NetworkRequest fixes

---

MADE.App.Views.Controls.TextEntry.Forms/MADE.App.Views.Controls.TextEntry.Forms.csproj
MADE.App.Views.Controls.TextEntry.Forms/TextEntry.xaml
MADE.App.Views.Controls.TextEntry.Forms/TextEntry.xaml.cs
MADE.App.sln
MADE.Samples.Forms/MADE.Samples.Forms/MADE.Samples.Forms.csproj
MADE.Samples.Forms/MADE.Samples.Forms/MainPage.xaml
MADE.Samples.Forms/MADE.Samples.Forms/MainPage.xaml.cs

Added in a text entry control for Xamarin.Forms which has a header. This also has the ability to change orientation if needed for the users application. The user will have the ability to customise/bind to the following properties:
- Header text
- Header style
- Input text
- Input text style
- Orientation
No associated issues.

Added in a Text Entry control with a header.

---

MADE.App.Design/MADE.App.Design.csproj
MADE.App.Diagnostics/MADE.App.Diagnostics.csproj
MADE.App.Views.Controls.HeaderedTextBlock.Forms/MADE.App.Views.Controls.HeaderedTextBlock.Forms.csproj
MADE.App.Views.Controls.HeaderedTextBlock/MADE.App.Views.Controls.HeaderedTextBlock.csproj
MADE.App.Views.Controls.TextEntry.Forms/MADE.App.Views.Controls.TextEntry.Forms.csproj
MADE.App.Views.Dialogs/MADE.App.Views.Dialogs.csproj
MADE.App.Views.Navigation.MvvmLight/MADE.App.Views.Navigation.MvvmLight.csproj
MADE.App.Views.Navigation/MADE.App.Views.Navigation.csproj
MADE.App.Views.Xamarin.Forms/MADE.App.Views.Xamarin.Forms.csproj
MADE.App.Views/MADE.App.Views.csproj
MADE.App/MADE.App.csproj
MADE.Samples.Android/MADE.Samples.Android.csproj
MADE.Samples.Android/Resources/Resource.Designer.cs
MADE.Samples.Forms/MADE.Samples.Forms.Android/MADE.Samples.Forms.Android.csproj
MADE.Samples.Forms/MADE.Samples.Forms.Android/Resources/Resource.designer.cs
MADE.Samples.Forms/MADE.Samples.Forms.UWP/MADE.Samples.Forms.UWP.csproj
MADE.Samples.Forms/MADE.Samples.Forms.iOS/MADE.Samples.Forms.iOS.csproj
MADE.Samples.Forms/MADE.Samples.Forms/MADE.Samples.Forms.csproj
MADE.Samples.Windows/MADE.Samples.Windows.csproj
MADE.Samples/MADE.Samples.csproj
MADE.UnitTests/MADE.UnitTests.csproj

This PR includes changes to the libraries projects to update their NuGet packages to the latest versions.
Packages changed include:
- Microsoft.NETCore.UniversalWindowsPlatform
- Xamarin.Forms
- Xamarin.Android.Support libraries
- CommonServiceLocator
#49 - Update NuGet package references to latest versions

PR for #49 - Updated NuGet packages to latest version

---

MADE.App.Diagnostics/AppDiagnostics.cs
MADE.App.Diagnostics/Exceptions/ExceptionObservedEventArgs.cs
MADE.App.Diagnostics/Exceptions/ExceptionObservedEventHandler.cs
MADE.App.Diagnostics/Exceptions/UncaughtExceptionHandler.Android.cs
MADE.App.Diagnostics/IAppDiagnostics.cs
MADE.App.Diagnostics/Logging/EventLogger.cs
MADE.App.Diagnostics/Logging/IEventLoggerExtras.cs
MADE.App.Diagnostics/Logging/StorageFileEventListener.Windows.cs
MADE.App.Diagnostics/MADE.App.Diagnostics.csproj

**Describe the changes made**
This PR includes changes to implement custom properties to set the file name and folder name for the EventLogger.
It also includes a change to support Android and Java exception handling in the AppDiagnostics component, as well as changes to support passing observed exceptions thrown to listeners attached via an event handler.
**What issues are associated?**
#52 Improvement to application diagnostics

PR for #52 - Implemented changes to event logger and AppDiagnostics

---

MADE.App.Views.Navigation/Pages/Page.Android.cs
MADE.App.Views.Navigation/Pages/Page.Windows.cs
MADE.App.Views/Controls/Control.Android.cs
MADE.App.Views/Controls/Control.Windows.cs
MADE.App.Views/Controls/Control.iOS.cs
MADE.App.Views/IView.Android.cs
MADE.App.Views/IView.cs
MADE.App.Views/IView.iOS.cs

**Describe the changes made**
This PR includes a change to the IView and relevant implementations to include a set of core event handlers for managing the events of when the IsVisible and IsEnabled state have changed.
This is a breaking change as it will require third-parties to implement the additional event handlers if they have created components built on the IView interface.
**What issues are associated?**
#56 - Add control event handlers for enabled and visible state change

Added changes to support control visible/enabled event handlers

---

MADE.App.Diagnostics/MADE.App.Diagnostics.csproj
MADE.App.Mvvm.UnitTests/MADE.App.Mvvm.UnitTests.csproj
MADE.App.Views.Controls.HeaderedTextBlock.Forms/MADE.App.Views.Controls.HeaderedTextBlock.Forms.csproj
MADE.App.Views.Controls.HeaderedTextBlock/MADE.App.Views.Controls.HeaderedTextBlock.csproj
MADE.App.Views.Controls.TextEntry.Forms/MADE.App.Views.Controls.TextEntry.Forms.csproj
MADE.App.Views.Dialogs/MADE.App.Views.Dialogs.csproj
MADE.App.Views.Navigation.MvvmLight/MADE.App.Views.Navigation.MvvmLight.csproj
MADE.App.Views.Navigation/MADE.App.Views.Navigation.csproj
MADE.App.Views.Xamarin.Forms/MADE.App.Views.Xamarin.Forms.csproj
MADE.App.Views/MADE.App.Views.csproj
MADE.App/MADE.App.csproj

> Please check one or more that apply to this PR
> Please describe, in detail, the changes made
- Updated the NuGet packages for the project to the latest version.
- Changed MvvmLightLibs out for the MADE App Component multi-target .NET Standard variant
> Please check one or more that apply for this PR
> Please check if your PR fulfils the following requirements:
> If this PR contains a breaking change, please describe the impact and migration path below. Please note that breaking changes are likely to be rejected
- No breaking changes made
> If you have other relevant information for this PR, please feel free to add below or remove this section if not
- No additional references

Updated NuGet packages

---

src/MADE.UI.Controls.Validator/InputValidator.cs

> Please check one or more that apply to this PR
Replaced string concatenation in validator feedback message text with string.Join().
> Please check if your PR fulfils the following requirements:
> If this PR contains a breaking change, please describe the impact and migration path below. Please note that breaking changes are likely to be rejected
- 
Is related to issue #111.
-

Validator feedback massages concatenation with string.Join().

---

.github/workflows/ci.yml
Directory.Build.props
samples/MADE.Samples/MADE.Samples.UWP/MADE.Samples.UWP.csproj
samples/MADE.Samples/MADE.Samples.Wasm/MADE.Samples.Wasm.csproj
src/MADE.Data.EFCore/IEntityBase.cs
src/MADE.Data.EFCore/MADE.Data.EFCore.csproj
src/MADE.UI.Controls.FilePicker/FilePickerItem.cs
src/MADE.Web.Mvc/MADE.Web.Mvc.csproj
src/MADE.Web/MADE.Web.csproj
tests/MADE.Collections.Tests/MADE.Collections.Tests.csproj
tests/MADE.Data.Converters.Tests/MADE.Data.Converters.Tests.csproj
tests/MADE.Data.Validation.Tests/MADE.Data.Validation.Tests.csproj
tests/MADE.Diagnostics.Tests/MADE.Diagnostics.Tests.csproj
tests/MADE.Networking.Tests/MADE.Networking.Tests.csproj
tests/MADE.Web.Tests/MADE.Web.Tests.csproj

Updated NuGet package references.
Includes adding support for .NET 6 in ASP.NET Core libraries. Both ASP.NET Core libraries have also been updated to take advantage of all the goodness of .NET 5 and .NET 6.

Updated package references

---

samples/MADE.Samples/MADE.Samples.Droid/MADE.Samples.Droid.csproj
samples/MADE.Samples/MADE.Samples.UWP/MADE.Samples.UWP.csproj
samples/MADE.Samples/MADE.Samples.Wasm/LinkerConfig.xml
samples/MADE.Samples/MADE.Samples.Wasm/MADE.Samples.Wasm.csproj
samples/MADE.Samples/MADE.Samples.iOS/MADE.Samples.iOS.csproj
src/MADE.UI.Controls.FilePicker/MADE.UI.Controls.FilePicker.csproj
src/MADE.UI.Controls.Validator/MADE.UI.Controls.Validator.csproj
src/MADE.UI.Styling/MADE.UI.Styling.csproj
src/MADE.UI.ViewManagement/MADE.UI.ViewManagement.csproj
src/MADE.UI.Views.Dialogs/MADE.UI.Views.Dialogs.csproj
src/MADE.UI.Views.Navigation.Mvvm/MADE.UI.Views.Navigation.Mvvm.csproj
src/MADE.UI.Views.Navigation/MADE.UI.Views.Navigation.csproj
src/MADE.UI/MADE.UI.csproj
tests/MADE.Collections.Tests/MADE.Collections.Tests.csproj
tests/MADE.Data.Converters.Tests/MADE.Data.Converters.Tests.csproj
tests/MADE.Data.Validation.Tests/MADE.Data.Validation.Tests.csproj
tests/MADE.Diagnostics.Tests/MADE.Diagnostics.Tests.csproj
tests/MADE.Networking.Tests/MADE.Networking.Tests.csproj
tests/MADE.Web.Tests/MADE.Web.Tests.csproj

Updated the Uno NuGet package references to v4 🤩

Updated Uno to v4

---

docs/index.md
docs/templates/material/styles/main.css

Fixed issue with layout styling for article pages

Updated styling for grid bordering system

---

samples/MADE.Samples/MADE.Samples.Droid/MADE.Samples.Droid.csproj
samples/MADE.Samples/MADE.Samples.UWP/MADE.Samples.UWP.csproj
samples/MADE.Samples/MADE.Samples.Wasm/MADE.Samples.Wasm.csproj
samples/MADE.Samples/MADE.Samples.iOS/MADE.Samples.iOS.csproj
src/MADE.Data.EFCore/MADE.Data.EFCore.csproj
src/MADE.UI.Controls.FilePicker/MADE.UI.Controls.FilePicker.csproj
src/MADE.UI.Controls.Validator/MADE.UI.Controls.Validator.csproj
src/MADE.UI.Styling/MADE.UI.Styling.csproj
src/MADE.UI.ViewManagement/MADE.UI.ViewManagement.csproj
src/MADE.UI.Views.Dialogs/MADE.UI.Views.Dialogs.csproj
src/MADE.UI.Views.Navigation.Mvvm/MADE.UI.Views.Navigation.Mvvm.csproj
src/MADE.UI.Views.Navigation/MADE.UI.Views.Navigation.csproj
src/MADE.UI/MADE.UI.csproj
tests/MADE.Collections.Tests/MADE.Collections.Tests.csproj
tests/MADE.Data.Converters.Tests/MADE.Data.Converters.Tests.csproj
tests/MADE.Data.Validation.Tests/MADE.Data.Validation.Tests.csproj
tests/MADE.Diagnostics.Tests/MADE.Diagnostics.Tests.csproj
tests/MADE.Networking.Tests/MADE.Networking.Tests.csproj
tests/MADE.Web.Tests/MADE.Web.Tests.csproj

Updated to latest EF Core version for netcore3.1, 5, and 6. 
Also updated Uno Platform packages to latest version, as well as the NUnit testing adapter

NuGet package update

---

src/MADE.Web/Extensions/ApiVersioningExtensions.cs
src/MADE.Web/MADE.Web.csproj

Changes have been made to introduce extensions to simplify the approach to enabling API versioning for web APIs.

Added API versioning extensions for .NET 5 applications

---

src/MADE.Data.EFCore/MADE.Data.EFCore.csproj

Updated the references for EF Core (super to #217)

Updated EF package

---

src/MADE.Data.Validation.FluentValidation/FluentValidatorCollection{T}.cs

Changes have been made to alter the collection based constructor for the FluentValidatorCollection to support the IValidator interface.

Added IValidator support to constructor for FluentValidatorCollection

---

src/MADE.Data.EFCore/MADE.Data.EFCore.csproj
tests/MADE.Collections.Tests/MADE.Collections.Tests.csproj
tests/MADE.Data.Converters.Tests/MADE.Data.Converters.Tests.csproj
tests/MADE.Data.Validation.FluentValidation.Tests/MADE.Data.Validation.FluentValidation.Tests.csproj
tests/MADE.Data.Validation.Tests/MADE.Data.Validation.Tests.csproj
tests/MADE.Diagnostics.Tests/MADE.Diagnostics.Tests.csproj
tests/MADE.Networking.Tests/MADE.Networking.Tests.csproj
tests/MADE.Web.Tests/MADE.Web.Tests.csproj

Changes made to update EF Core packages to latest versions

Updated packages

---

docs/articles/features/data-validation.md
src/MADE.Data.Validation/MADE.Data.Validation.csproj
src/MADE.Data.Validation/Strings/Resources.Designer.cs
src/MADE.Data.Validation/Strings/Resources.resx
src/MADE.Data.Validation/Validators/Base64Validator.cs
src/MADE.Data.Validation/Validators/BetweenValidator.cs
src/MADE.Data.Validation/Validators/GuidValidator.cs
src/MADE.Data.Validation/Validators/LatitudeValidator.cs
src/MADE.Data.Validation/Validators/LongitudeValidator.cs
src/MADE.Data.Validation/Validators/MacAddressValidator.cs
src/MADE.Data.Validation/Validators/PredicateValidator{T}.cs
src/MADE.Data.Validation/Validators/RegexValidator.cs
src/MADE.Data.Validation/Validators/WellFormedUrlValidator.cs
tests/MADE.Data.Validation.Tests/Tests/Base64ValidatorTests.cs
tests/MADE.Data.Validation.Tests/Tests/BetweenValidatorTests.cs
tests/MADE.Data.Validation.Tests/Tests/GuidValidatorTests.cs
tests/MADE.Data.Validation.Tests/Tests/LatitudeValidatorTests.cs
tests/MADE.Data.Validation.Tests/Tests/LongitudeValidatorTests.cs
tests/MADE.Data.Validation.Tests/Tests/MacAddressValidatorTests.cs
tests/MADE.Data.Validation.Tests/Tests/PredicateValidatorTests.cs
tests/MADE.Data.Validation.Tests/Tests/WellFormedUrlValidatorTests.cs

Changes have been made to introduce new data validators into the `Data.Validators` package including:
- Base64 string validator
- GUID validator
- Latitude/Longitude validators
- MAC address validator
- Predicate validator
- Well-formed URL validator
Additional changes have been made to the following validators:
- Between validator updated with inclusivity flag

Added collection of new data validators

---

src/MADE.Collections/CollectionExtensions.cs
src/MADE.Collections/DictionaryExtensions.cs
src/MADE.Data.Converters/Extensions/CollectionExtensions.cs
src/MADE.Data.Converters/Extensions/LengthExtensions.cs
src/MADE.Runtime/Extensions/ReflectionExtensions.cs
tests/MADE.Collections.Tests/Tests/CollectionExtensionsTests.cs
tests/MADE.Data.Converters.Tests/Tests/CollectionExtensionsTests.cs

Changes have been made to introduce additional extensions for collections that have been useful in recent projects.

Port of usable components from personal archived projects

---

.github/PULL_REQUEST_TEMPLATE.md
src/MADE.Data.EFCore/MADE.Data.EFCore.csproj
src/MADE.Data.Validation.FluentValidation/MADE.Data.Validation.FluentValidation.csproj

Minor change to rev dependencies with minor changes.

Updated minor version for dependencies

---

src/MADE.Data.EFCore/MADE.Data.EFCore.csproj
src/MADE.Data.Validation.FluentValidation/MADE.Data.Validation.FluentValidation.csproj
tests/MADE.Collections.Tests/MADE.Collections.Tests.csproj
tests/MADE.Data.Converters.Tests/MADE.Data.Converters.Tests.csproj
tests/MADE.Data.Serialization.Tests/MADE.Data.Serialization.Tests.csproj
tests/MADE.Data.Validation.FluentValidation.Tests/MADE.Data.Validation.FluentValidation.Tests.csproj
tests/MADE.Data.Validation.Tests/MADE.Data.Validation.Tests.csproj
tests/MADE.Diagnostics.Tests/MADE.Diagnostics.Tests.csproj
tests/MADE.Networking.Tests/MADE.Networking.Tests.csproj
tests/MADE.Web.Tests/MADE.Web.Tests.csproj

Fixes the dependabot PRs for dependency changes

Updated dependencies

---

src/MADE.Data.EFCore/MADE.Data.EFCore.csproj
src/MADE.Data.Validation.FluentValidation/MADE.Data.Validation.FluentValidation.csproj
tests/MADE.Collections.Tests/MADE.Collections.Tests.csproj
tests/MADE.Data.Converters.Tests/MADE.Data.Converters.Tests.csproj
tests/MADE.Data.EFCore.Tests/MADE.Data.EFCore.Tests.csproj
tests/MADE.Data.Serialization.Tests/MADE.Data.Serialization.Tests.csproj
tests/MADE.Data.Validation.FluentValidation.Tests/MADE.Data.Validation.FluentValidation.Tests.csproj
tests/MADE.Data.Validation.Tests/MADE.Data.Validation.Tests.csproj
tests/MADE.Diagnostics.Tests/MADE.Diagnostics.Tests.csproj
tests/MADE.Networking.Tests/MADE.Networking.Tests.csproj
tests/MADE.Web.Tests/MADE.Web.Tests.csproj

Changes have been made to update dependencies of main EF projects and test dependencies.

⬆️ Updated dependencies
